# Development version of configuration

# Database connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authapp
    username: postgres
    password: postgres@123

#    hikari:
#      pool-name: HikariCP-Dev
#      maximum-pool-size: 5
#      minimum-idle: 2
#      connection-timeout: 20000
#      idle-timeout: 120000
#      max-lifetime: 900000
#      validation-timeout: 3000
#      leak-detection-threshold: 2000
#      initialization-fail-timeout: -1

# JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# oauth 2 configurations

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:TEST_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:TEST_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid


logging:
  level:
    org.springframework.security: DEBUG


security:
  jwt:
    secret: ${JWT_SECRET:a-valid-string-secret-that-is-at-least-512-bits-long-which-is-very-long}
    issuer: ${JWT_ISSUER:api.lokeshkaushik.in}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}